name: Build Echo From Source

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-build:
    runs-on: macos-latest
    env:
      CI: false
      GH_TOKEN: ${{ secrets.SECRET_GH_TOKEN }}
      CSC_LINK: ${{ secrets.SECRET_CSC_LINK }}
      

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run electron:build
